#!/usr/bin/env bash

cd ..
git stash
# sw: can check this output to run updates based on cron jobs
# git remote update
# git status -uno
git pull
cd backend

if [ "$#" -gt 0 ] # if greater than 0
then
  npm update
fi

npm run build

if [ "$#" -gt 0 ] # if greater than 0
then
  # only run if npm update was run
  # https://pm2.keymetrics.io/docs/usage/signals-clean-restart/
  # pm2 restart npm -- run watch --max-memory-restart 1000M # causes weird restarts
  # pm2 reload npm -- run watch --env production --source-map-support --wait-ready
  # pm2 reload npm -- run watch --source-map-support --node-args="--max_old_space_size=4096"
  pm2 reload npm -- run serve --source-map-support --node-args="--max_old_space_size=2048"
fi

# restart cron service
./server/render_sheets
/etc/init.d/cron restart
