#!/usr/bin/env bash
 
goaccess /var/log/caddy/access.log \
  --html-pref='{"theme":"darkBlue","perPage":50,"layout":"vertical","showTables":true,"visitors":{"plot":{"chartType":"area-spline"}}}' \
  -o /vol/static/analytics.html \
  --http-protocol=no \
  --with-mouse \
  --hl-header \
  --with-output-resolver \
  --ignore-crawlers \
  --all-static-files \
  --log-format=CADDY \
  --sort-panel=REQUESTS,BY_VISITORS,DESC
  
