version: '3.3'
services:
    mariadb:
        container_name: mariadb
        volumes:
            - '/vol/docker/mysql/datadir:/var/lib/mysql'
            - '/vol/docker/mysql/my.cnf:/etc/mysql/my.cnf'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=<your_db_pass>
            - MYSQL_DATABASE=test
        image: mariadb:10.4.17
    portainer:
        container_name: portainer
        ports:
            - '9000:9000'
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/opt/portainer:/data'
        image: portainer/portainer
    caddy:
        container_name: caddy
        command: cd /var/log | mkdir caddy | chown caddy caddy
        ports:
            - '80:80'
            - '443:443'
        environment:
            - ACME_AGREE=true
        volumes:
            - '/vol/docker/caddy/log:/var/log'
            - '/vol/docker/caddy/Caddyfile:/etc/Caddyfile'
            - '/vol/docker/caddy/srv:/srv'
            - '/vol/docker/caddy/certs:/root/.caddy'
        image: abiosoft/caddy