version: '3.3'
services:
    mariadb:
        container_name: mariadb
        volumes:
            - '/Users/kakisu/Desktop/drafty-db:/var/lib/mysql'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=testpassword
            - MYSQL_DATABASE=csprofessors
        image: mariadb
    phpmyadmin:
        container_name: myadmin
        links:
            - 'mariadb:db'
        ports:
            - '8888:80'
        image: phpmyadmin/phpmyadmin
    # portainer:
    #     container_name: portainer
    #     ports:
    #         - '9000:9000'
    #     restart: always
    #     volumes:
    #         - '/var/run/docker.sock:/var/run/docker.sock'
    #         - '/opt/portainer:/data'
    #     image: portainer/portainer
