version: '3.3'
services:
    mariadb:
        container_name: mariadb
        volumes:
            - '<your_data_directory>:/var/lib/mysql'
            - './mysql/config/my.cnf:/etc/mysql/my.cnf'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=testpassword
            - MYSQL_DATABASE=csprofessors
        image: mariadb
